### PR TITLE
fix: do not try to store contacts not matching pubkey regex in wrapper

### LINKED ISSUE #2872: [BUG] Trailing space at end of address causes Session to not progress past splash screen
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Session is currently not starting on desktop, and I found this error when I ran the appimage from the command line.

{"name":"log","hostname":"toaster-oven","pid":2297076,"level":50,"msg":"Error received from worker job 440 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 05e998a1ee8fa8ed675e709110d4e27c5bee4fdddf9645a0a37c2ce6b773419828 ","time":"2023-08-22T11:10:16.224Z","v":0}
{"name":"log","hostname":"toaster-oven","pid":2297076,"level":30,"msg":"Worker job 440 (ContactsConfig) failed in 0ms with Error received from worker job 440 (ContactsConfig): Invalid session ID: expected 66 hex digits starting with 05; got 05e998a1ee8fa8ed675e709110d4e27c5bee4fdddf9645a0a37c2ce6b773419828 ","time":"2023-08-22T11:10:16.225Z","v":0}

It looks like a space was somehow put onto the end of the key, most likely when it was stored in the database, and it's tripping up the ContactsConfig worker when it reads from there. Because my database file is encrypted with a password, I am unsure as to how to unlock the database to remove the whitespace (per what was done by the reporter for #2868). I am thus unable to proceed further than the splash screen after typing in the password.

This originally happened on version 1.10.0. I attempted to remedy it by compiling the application from source and then placing the files from the original Session config folder into the Session-production-devprod config folder that was generated upon startup. The devprod version is where the above error message was taken from.

### Expected Behavior

It should trim whitespace from both ends before storing keys into the database, and ideally it should trim whitespace it finds as it reads from the database.

### Steps To Reproduce

I am unsure how exactly this happened. The ID that has a whitespace was added some time before the application started doing this. I believe this behavior started after I restarted the application after it was open for a time.

### Desktop Version

1.11.0; also the most recent commit compiled from source as of time of writing

### Anything else?

_No response_

### LINKED ISSUE #2916: [BUG] Session not loading
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-desktop/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ive used session for a couple of days without problems but since 2 days ago it wont load. After launching the program i only get to the logo screen with the S and then nothing more happens ive let it run for hours and still nothing still stuck on splash screen

### Expected Behavior

The app acutally loading 

### Steps To Reproduce

1. click the shortcut/exe file
2. it not loading

### Desktop Version

v1.11.2

### Anything else?

Windows 11, version 22H2

### PR DESCRIPTION
**Pull request by Bilb**
Fixes #2916
Fixes #2872

### CODE REVIEW

File: ts/node/sql.ts [hunk 1]
```diff
@@ -620,11 +620,29 @@ function getAllConversations() {
...
+  const formatted = compact(
+    (rows || []).map(m => {
+      const unreadCount = getUnreadCountByConversation(m.id) || 0;
+      const mentionedUsStillUnread = !!getFirstUnreadMessageWithMention(m.id);
+      return formatRowOfConversation(m, 'getAllConversations', unreadCount, mentionedUsStillUnread);
+    })
+  );
+
+  const invalidOnLoad =
+    formatted.filter(m => {
```
Comment (yougotwill) [inline ts/node/sql.ts:633]: Wont filter just return an empty array is no item pass the boolean check? do you still need `|| []` ?

File: ts/test/session/unit/libsession_wrapper/libsession_wrapper_contacts_test.ts [hunk 2]
```diff
@@ -137,6 +137,45 @@ describe('libsession_contacts', () => {
...
+        '050123456789abcdef050123456789abcdef0123456789abcdef050123456789a '; // len 66 but has a ' ' at the end
+      expect(
+        SessionUtilContact.isContactToStoreInWrapper(
+          new ConversationModel({
+            ...validArgs,
+            id: validIdWithSpaceInIt,
+          } as any)
+        )
+      ).to.be.eq(false);
+    });
```
Comment (yougotwill) [inline ts/test/session/unit/libsession_wrapper/libsession_wrapper_contacts_test.ts:164]: What about space at the beginning? Although I don't think it will make a difference

**Review by yougotwill — CHANGES_REQUESTED** [review]

**Review by yougotwill — APPROVED** [review]
LGTM
