### PR TITLE
Fix the conversation horizontal scrollbar when only few conversations #560

### LINKED ISSUE #560: Opening the profile settings drop down causes scroll bar in conversations
Even if you have very few conversations, when you click on the button on your name to view other menu options vertical and horizontal scroll bars are appearing in the conversation list div

### LINKED ISSUE #1146: Opening the profile settings drop down causes scroll bar in conversations
Even if you have very few conversations, when you click on the button on your name to view other menu options vertical and horizontal scroll bars are appearing in the conversation list div

### PR DESCRIPTION
**Pull request by Bilb**
### First time contributor checklist:

* [X] I have read the [README](https://github.com/signalapp/Signal-Desktop/blob/master/README.md) and [Contributor Guidelines](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md)
* [X] I have signed the [Contributor Licence Agreement](https://signal.org/cla/)

### Contributor checklist:

* [X] My contribution is **not** related to translations. _Please submit translation changes via our [Signal Desktop Transifex project](https://www.transifex.com/signalapp/signal-desktop/)._
* [X] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [X] My changes are [rebased](https://medium.freecodecamp.org/git-rebase-and-the-golden-rule-explained-70715eccc372) on the latest [`development`](https://github.com/signalapp/Signal-Desktop/tree/development) branch
* [ ] A `yarn ready` run passes successfully ([more about tests here](https://github.com/signalapp/Signal-Desktop/blob/master/CONTRIBUTING.md#tests))
* [X] My changes are ready to be shipped to users

**Yarn ready does not pass but I do not think it comes from this issue:** 

```
 /Pro/contribs/loki-messenger/js/modules/loki_file_server_api.js
233:43  error  'DEVICE_MAPPING_ANNOTATION_KEY' is not defined  no-undef
```

### Description
Do not show a vertical scrollbar when there are not enough conversations in the conversation list.
Fixes oxen-io/session-desktop-temp#1037 

Tested manually, screenshots provided.

Tested on Linux 64-bit (Debian)

Attached, some screenshots of before and after behavior.
**Before**: even if only 3 items in the list, when the dropdown menu is shown the list shows a scrollbar (the list does not resize):
before

**After**: the scrollbar is not visible when not enough items are on the list and the dropdown menu is shown;
after

**After**: the vertical scrollbar works as expected and the horizontal one is no longer visible:
after2

### CODE REVIEW

**Review by msgmaxim — APPROVED** [review]

**Comment by msgmaxim** [comment]
Looks good to me! Yeah, the `DEVICE_MAPPING_ANNOTATION_KEY` is fixed in #657.

**Review by sachaaaaa — APPROVED** [review]
LGTM

File: ts/components/LeftPane.tsx [hunk 1]
```diff
@@ -237,6 +237,7 @@ export class LeftPane extends React.Component<Props, any> {
               rowHeight={64}
               rowRenderer={this.renderRow}
               width={width}
+              autoHeight
```
Comment (sachaaaaa) [inline ts/components/LeftPane.tsx]: Linter is complaining, you might need to assign something to autoHeight?
```
/Users/travis/build/loki-project/loki-messenger/ts/components/LeftPane.tsx:240:15
ERROR: 240:15  jsx-boolean-value  Value must be set for boolean attributes
```

**Comment by Bilb** [comment]
fixing lint

File: ts/components/LeftPane.tsx (hunk 1 above)
Comment (Bilb) [reply ts/components/LeftPane.tsx]: Fixed it

Comment (sachaaaaa) [reply ts/components/LeftPane.tsx]: Awsome!

**Review by Mikunj — APPROVED** [review]
